Update to latest dev version
apepper/scrivito-icon-editor pull request #1
Opened 2024-10-11 19:10 UTC by dcsaszar

2024-10-14 09:19 UTC, apepper requested changes
FEEDBACK ([2b19471](https://github.com/apepper/scrivito-icon-editor/pull/1/commits/2b19471676a04ae11ccd4fb5e435ac177de9c7c6))

Very nice 🚀!

Please see my comments for further improvements.

2024-10-14 09:19 UTC, apepper commented on src/IconPicker.tsx
> +      {!disabled && (
With `!disabled` the editor looks a bit broken:

<img width="1624" alt="Screenshot 2024-10-14 at 11 05 22" src="https://github.com/user-attachments/assets/f7b6f9e0-e0b2-495b-b00b-ff8451959bca">

2024-10-14 09:19 UTC, apepper commented on src/BootstrapIconPicker.tsx
> +import 'bootstrap-icons/font/bootstrap-icons.css'
Does plain typescript compile support `with { type: 'json' }` and importing a `css` file?

2024-10-14 13:08 UTC, dcsaszar commented on README.md
> +    }),
The editing config expects a component, which has consequences:
1. It's not possible to pass custom props without wrapper component boilerplate: `component: (props) => <ScrivitoBootstrapIconEditorWithOptions myProp="foo" {...props} />`
2. The wrapper boilerplate requires a change of the editing config from TS to TSX (or using the `jsx` helper syntax)
3. AFAICS it's not possible or at least not trivial to have a single component instead of two anyway `ScrivitoBootstrapIconEditor` and `ScrivitoBootstrapIconEditorWithOptions`

Thus, the idea of the get helper is to make custom props more convenient to use.

2024-10-14 13:13 UTC, dcsaszar commented on src/ScrivitoBootstrapIconEditor.tsx
> +        className={`scrivito_${theme} scrivito_detail_content icon-editor-tab`}
The current implementation relies on styles and classes from
* https://github.com/Scrivito/scrivito_example_app_js/blob/45e38d2f8a46c1079111951d6a68b6e250df9f1f/src/assets/stylesheets/_scrivito_extensions.scss or
* https://github.com/Scrivito/scrivito-portal-app/blob/ad9870e5a8128b04390dbe93302e4fdd831ae2ab/src/assets/stylesheets/scrivitoExtensions.scss

If required, we could make it standalone by copying the necessary styles.

2024-10-14 13:14 UTC, dcsaszar commented on src/IconPicker.tsx
> +    <div className="icon-picker">
The idea here is to have support for custom styling. Since a div is not semantic we give the element a class name to be easily selectable.

2024-10-14 13:17 UTC, dcsaszar commented on src/ScrivitoBootstrapIconEditor.tsx
> +        className={`scrivito_${theme} scrivito_detail_content icon-editor-tab`}
Yes,
* The `Scrivito*` components have styling optimized for scrivito
* The lower level components only have default styling and can/should be customized with app-specific CSS

2024-10-14 13:32 UTC, dcsaszar commented on src/BootstrapIconPicker.tsx
> +import 'bootstrap-icons/font/bootstrap-icons.css'
* `type: 'json'` is supported in Node but gives an "experimental" warning
* `.css` is not supported by default. To make this more versatile we could either force users to import the CSS manually, and/or only import it (dynamically?) in the Scrivito specific components.

2024-10-14 14:04 UTC, dcsaszar commented on README.md
> +- **showClearButton**: (boolean) If true, shows a button to clear the selected icon. Default: false
How exactly should the component behave with regards to such a `defaultValue`?
E.g. what happens if `showClearButton` and `defaultValue` are given at the same time?

2024-10-14 17:00 UTC, dcsaszar commented on src/IconPicker.tsx
> +      {!disabled && (
cf13f47

2024-10-14 17:00 UTC, dcsaszar commented on README.md
> +The `scrivito-icon-editor` is a versatile icon picker designed for seamless integration with [Scrivito](https://www.scrivito.com) and React applications. It supports Bootstrap Icons out of the box bu
946332d

2024-10-14 17:00 UTC, dcsaszar commented on README.md
> +  )
946332d

2024-10-14 17:00 UTC, dcsaszar commented on src/ScrivitoIconEditor.css
> +.icon-editor-tab {
7fffab7

2024-10-15 09:26 UTC, apepper commented on README.md
> +- **showClearButton**: (boolean) If true, shows a button to clear the selected icon. Default: false
If `defaultValue` is defined, `showClearButton: true` will be silently changed to `showClearButton: false`.

2024-10-23 12:44 UTC, dcsaszar commented
FYI 677db11 released as 0.0.1

2024-10-28 14:01 UTC, apepper commented
Great. Thank you so much for your work! I'll now delete this repo, since https://github.com/Scrivito/scrivito-icon-editor exists now.

2024-10-28 14:01 UTC, closed without merging